pxe + http fix
githedgehog/fabric pull request #465
Opened 2024-04-12 21:52 UTC by amitlimaye

fix for #463

2024-04-18 17:09 UTC, sergeymatov submitted a review, later dismissed
Please remove commented lines
Tested on Env-1, worked for both HTTP/TFTP

2024-04-18 17:24 UTC, Frostman requested changes

2024-04-18 17:24 UTC, Frostman commented on pkg/dhcpd/dhcphandlers.go
> +			//resp.Options.Update(dhcpv4.OptBootFileName(u.String()))
please, remove debug? comments

2024-04-18 17:24 UTC, Frostman commented on pkg/dhcpd/dhcphandlers.go
> +			//resp.Options.Del(dhcpv4.
same

2024-04-24 16:03 UTC, Frostman approved these changes

2024-04-24 16:56 UTC, merged